/*
 * metal_detector.c - PI metal detector sequencer (stm_detector3, STM32G474)
 *
 * HARDWARE-TIMELINE ARCHITECTURE (rev 2)
 *
 * All four timers run one shared absolute timeline in one-pulse mode,
 * started by a single hardware trigger. No ISR sits between any two
 * critical edges, so Set A and Set B align to one timer clock (~6 ns)
 * and blanking is exact and identical every cycle.
 *
 *   TIM2  master: TRGO = counter-enable (MMS=Enable). Set A TX on CH1.
 *   TIM3  slave (trigger mode, ITR1 = TIM2_TRGO): Set B TX on CH1.
 *   TIM1  slave (ITR1): Set A aux (CH2 gain / CH3 integ / CH4 RX).
 *   TIM8  slave (ITR1): Set B aux (CH1 gain / CH3 integ / CH4N RX).
 *
 * All PSC=0 → 170 MHz ticks. Timeline (md_start_cycle sets TIM2 CEN;
 * every armed slave starts in the same kernel clock):
 *
 *   t = 1 tick            TX pins HIGH   (PWM2 compare, CCR=1)
 *   t = tx                TX pins LOW    (TX timers' OPM update; they stop)
 *                         (tx = coil charge time, f/v keys 10-120 µs, dfl 120)
 *   t = tx + bl           gain HIGH, integ HIGH, RX pins connect
 *                         (aux compares, one CCR value — same clock, both sets)
 *   t = tx + bl + rx      RX pins disconnect (aux OPM update clears the PWM2
 *                         ref in hardware); TIM1's UIE starts the ADC reads.
 *   + ~3 µs               all four ADCs finish their 2-channel injected
 *                         sequences (all 8 inputs, every cycle, regardless of
 *                         fire mode); the last JEOS releases gain + integ —
 *                         deliberately non-critical (integrators hold until
 *                         they have been sampled).
 *
 * ADC plan: each ADC converts its own pin pair as a software-started
 * injected sequence (results in JDR1/JDR2 — no DMA). TIM1 always runs the
 * timeline (its outputs are just idled in B-only mode), so its UIE kicks
 * all four ADCs every cycle and adjacent-coil cross-reads come for free.
 *   ADC1: PA0/PA1 (IN1/IN2)    ADC2: PA6/PA7  (IN3/IN4)
 *   ADC3: PB1/PB13 (IN1/IN5)   ADC4: PB12/PB14 (IN3/IN4)
 *
 * TX channels use PWM mode 2 (ref = CNT >= CCR) with CCR = 1 tick: while a
 * timer sits stopped at CNT=0 the ref is LOW, so idle pins are safe — the
 * reason detector2 used force modes instead of plain PWM1. The RX-connect
 * channels use the same trick for a fully hardware 3 µs window: ref rises
 * at the aux compare and falls when the OPM update reloads CNT to 0.
 *
 * Gain/integ channels use Active-on-compare, which latches the ref HIGH
 * through the OPM stop — exactly what the integrator-hold requires.
 *
 * Fire modes gate ONLY the coil TX channels: gain/integ/RX on both sets
 * run the identical dual-mode timeline every cycle regardless (the quiet
 * set's receive chain listens to the other coil's pulse). Single-coil
 * operation alternates the TX between sets on successive cycles.
 *
 * Set A: TX=TIM2 CH1 (PA5), TIM1: CH2=PA9 gain, CH3=PA10 integ,
 *        CH4=PA11 RX connect (CC4P=1 inverts).
 * Set B: TX=TIM3 CH1 (PB4), TIM8: CH1=PA15 gain, CH3=PB9 integ,
 *        CH4N=PC13 RX connect (CC4NP=1 inverts; CC4NE/OIS4N bits).
 *
 * CubeMX still generates a baseline init (PSC=169, TIMING modes); this
 * module owns the final register state, as detector2's MD init did.
 */

#include "metal_detector.h"
#include "main.h"
#include "gps.h"      /* gps_passthrough_enabled ('G' key), module identity */
#include <stdio.h>
#include <string.h>

/* Generated by gen_version.sh (gitignored); builds without it still work
 * so a fresh clone compiles in the IDE before the pre-build step is set. */
#if __has_include("fw_version.h")
#include "fw_version.h"
#else
#define FW_GIT_HASH "unknown"
#endif

extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim8;
extern ADC_HandleTypeDef hadc1;
extern ADC_HandleTypeDef hadc2;
extern ADC_HandleTypeDef hadc3;
extern ADC_HandleTypeDef hadc4;
extern ADC_HandleTypeDef hadc5;

volatile uint32_t md_tx_pulse_us  = MD_TX_PULSE_US;   /* coil charge time */
volatile uint32_t md_blanking_us  = MD_BLANKING_US;
volatile uint32_t md_rx_window_us = MD_RX_WINDOW_US;
volatile uint32_t md_cycle_count  = 0;

/* Coil-array geometry — set at provisioning time (d/c keys + 'S' save),
 * reported by the 'I' info line so studies get tagged with the producing
 * unit's physical layout. The web visualizer combines these with the GPS
 * heading to place each coil's samples. */
volatile uint32_t md_coil_spacing_mm      = MD_COIL_SPACING_MM_DEFAULT;
volatile int32_t  md_coil_offset_fore_mm  = 0;   /* array center vs antenna */
volatile int32_t  md_coil_offset_right_mm = MD_COIL_OFFSET_RIGHT_MM_DEFAULT;

/* Fire mode (keys 1/2/3, persisted): which TX strobes run each cycle.
 * "odd" = set A only (PA5), "even" = set B only (PB4), "both" = normal.
 * Everything else — gain/integ/RX lines and all 8 ADC reads — is identical
 * in every mode (md_arm_set gates only the coil trigger). */
volatile uint8_t md_fire_mode = MD_FIRE_BOTH;

static const char *md_fire_name(uint8_t m)
{
    return (m == MD_FIRE_A) ? "odd" : (m == MD_FIRE_B) ? "even" : "both";
}

/* DWT cycle timestamps (debug aid) */
volatile uint32_t md_ts_cen;
volatile uint32_t md_ts_opm;

#define MD_TICKS_PER_US  170U     /* PSC=0 at 170 MHz timer clock */

/* Tuning limits: the aux timers are 16-bit at 170 MHz ticks, so
 * (tx + blanking + rx) must stay <= 385 us or ARR overflows — holds at
 * every limit (120 + 200 + 50 = 370). TX pulse capped at the old fixed
 * 120 us: longer charges overheat the TX FETs (f/v keys, bench tunable). */
#define MD_TX_PULSE_MIN_US   10U
#define MD_TX_PULSE_MAX_US   120U
#define MD_BLANKING_MAX_US   200U
#define MD_RX_WINDOW_MAX_US  50U

/* Coil geometry limits (sanity only — no hardware constraint) */
#define MD_COIL_SPACING_MM_MIN    50U
#define MD_COIL_SPACING_MM_MAX    5000U
#define MD_COIL_OFFSET_MM_LIMIT   5000

static inline uint32_t dwt_cyccnt(void)
{
    if (!(CoreDebug->DEMCR & CoreDebug_DEMCR_TRCENA_Msk))
        CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    if (!(DWT->CTRL & DWT_CTRL_CYCCNTENA_Msk))
        DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
    return DWT->CYCCNT;
}

/* ---------------------------------------------------------------------------
 * Per-set descriptor. Set B's gain-protect lives on CH1 (A: CH2), so CCMR
 * access is channel-indexed. Bit positions are identical H7 ↔ G4.
 * ------------------------------------------------------------------------- */
typedef struct {
    TIM_TypeDef *tx;        /* TX pulse timer; coil on CH1                  */
    TIM_TypeDef *opm;       /* aux one-pulse timer                          */
    uint8_t      gain_ch;   /* gain-protect release channel (A:2, B:1)     */
    uint8_t      integ_ch;  /* integrator enable channel (3 on both)        */
    uint8_t      rx_ch;     /* RX connect channel, inverted pol (4 on both) */
} md_set_t;

static md_set_t md_set_a = { TIM2, TIM1, 2, 3, 4 };
static md_set_t md_set_b = { TIM3, TIM8, 1, 3, 4 };

/* OCxM 3-bit mode values (extended 4th bit always 0 for these modes) */
#define MD_OCM_ACT_ON_CMP    1U   /* OCxREF→1 when CNT=CCRx, latches        */
#define MD_OCM_FORCE_INACT   4U   /* OCxREF=0 immediately                   */
#define MD_OCM_PWM2          7U   /* OCxREF=1 while CNT>=CCRx (self-clears
                                     at OPM update when CNT reloads to 0)   */

/* Write OCxM for channel ch (1..4): CH1/CH3 sit at bits [6:4]+[16] of
 * CCMR1/CCMR2, CH2/CH4 at bits [14:12]+[24]. */
static inline void md_oc_mode(TIM_TypeDef *tim, uint8_t ch, uint32_t mode)
{
    volatile uint32_t *ccmr = (ch <= 2) ? &tim->CCMR1 : &tim->CCMR2;
    uint32_t lo   = (ch & 1U) ? 4U : 12U;
    uint32_t ext  = (ch & 1U) ? 16U : 24U;
    uint32_t mask = (7U << lo) | (1U << ext);
    *ccmr = (*ccmr & ~mask) | (mode << lo);
}

/* CCRx for channel ch (1..4) — consecutive registers */
static inline void md_set_ccr(TIM_TypeDef *tim, uint8_t ch, uint32_t val)
{
    (&tim->CCR1)[ch - 1U] = val;
}

/* Slave a timer to TIM2_TRGO in trigger mode: counter starts in hardware
 * on the master's CEN rising edge. ITR1 = tim2_trgo for TIM1/TIM8
 * (RM0440 Table 267) and TIM3 (Table 291). */
static inline void md_slave_to_tim2(TIM_TypeDef *tim)
{
    tim->SMCR = (tim->SMCR & ~(TIM_SMCR_TS | TIM_SMCR_SMS))
                | TIM_TS_ITR1 | TIM_SLAVEMODE_TRIGGER;
}

/* ---------------------------------------------------------------------------
 * ADC: one injected pair per ADC, all four kicked together from TIM1's UIE.
 * md_adc[] order is the CSV order.
 * ------------------------------------------------------------------------- */
volatile uint16_t md_adc[MD_ADC_COUNT];
volatile uint8_t  md_adc_frame_ready = 0;

typedef struct {
    ADC_TypeDef *adc;
    uint8_t      ch1, ch2;  /* injected sequence: ch1 then ch2 (both 1..9)  */
    uint8_t      idx;       /* md_adc[idx] = ch1 result, [idx+1] = ch2      */
} md_adc_pair_t;

static const md_adc_pair_t md_adc_pairs[4] = {
    { ADC1, 1, 2, 0 },      /* PA0,  PA1  */
    { ADC2, 3, 4, 2 },      /* PA6,  PA7  */
    { ADC3, 1, 5, 4 },      /* PB1,  PB13 */
    { ADC4, 3, 4, 6 },      /* PB12, PB14 */
};

/* 0x0F = idle/complete; md_adc_kick clears it, each JEOS sets its bit.
 * The three ADC IRQs share priority 3, so they never preempt each other
 * and the read-modify-write below is race-free. */
static volatile uint8_t md_adc_done_mask = 0x0FU;

#define MD_ADC_SMP_47CYC5  4U   /* SMPR code: 47.5 ADC clocks @ 42.5 MHz    */

/* Calibrate, set sampling times, load the injected sequences, enable, and
 * unmask JEOS. CubeMX's HAL_ADC_Init already ran (regulator up, JQDIS=1,
 * independent mode); this owns the rest, per the module's override pattern. */
static void md_adc_init(void)
{
    ADC_HandleTypeDef *hs[4] = { &hadc1, &hadc2, &hadc3, &hadc4 };

    for (uint32_t i = 0; i < 4U; i++) {
        const md_adc_pair_t *p = &md_adc_pairs[i];

        HAL_ADCEx_Calibration_Start(hs[i], ADC_SINGLE_ENDED);

        /* Injected 16x oversampling, no shift: each JDR is the hardware
         * SUM of 16 conversions — max 16*4095 = 65520, so the values
         * still fit uint16_t end-to-end (md_adc[], CSV, daemon). ~2 more
         * effective bits for a ~16x longer sequence (~45 us/pair), which
         * the GPS-paced cadence has to spare. Full-register write also
         * evicts anything a debugger poke left behind (JADSTART is 0). */
        p->adc->CFGR2 = ADC_CFGR2_JOVSE | (3U << ADC_CFGR2_OVSR_Pos);

        uint32_t smpr = p->adc->SMPR1;      /* both channels are 1..9        */
        smpr &= ~((7U << (3U * p->ch1)) | (7U << (3U * p->ch2)));
        smpr |=  (MD_ADC_SMP_47CYC5 << (3U * p->ch1))
               | (MD_ADC_SMP_47CYC5 << (3U * p->ch2));
        p->adc->SMPR1 = smpr;

        /* JL=1 → 2 conversions; JEXTEN=0 → software start (JADSTART) */
        p->adc->JSQR = ADC_JSQR_JL_0
                     | ((uint32_t)p->ch1 << ADC_JSQR_JSQ1_Pos)
                     | ((uint32_t)p->ch2 << ADC_JSQR_JSQ2_Pos);

        p->adc->ISR = ADC_ISR_ADRDY;
        p->adc->CR |= ADC_CR_ADEN;
        while (!(p->adc->ISR & ADC_ISR_ADRDY)) {}
        p->adc->ISR = ADC_ISR_JEOS | ADC_ISR_JEOC;
        p->adc->IER |= ADC_IER_JEOSIE;
    }

    /* Below the timers (2), above the GPS UART (6). Handlers live in
     * stm32g4xx_it.c USER CODE 1 — CubeMX does not generate them. */
    HAL_NVIC_SetPriority(ADC1_2_IRQn, 3, 0);
    HAL_NVIC_EnableIRQ(ADC1_2_IRQn);
    HAL_NVIC_SetPriority(ADC3_IRQn, 3, 0);
    HAL_NVIC_EnableIRQ(ADC3_IRQn);
    HAL_NVIC_SetPriority(ADC4_IRQn, 3, 0);
    HAL_NVIC_EnableIRQ(ADC4_IRQn);
}

/* Hot path: start all four injected sequences (~4 register writes). */
static inline void md_adc_kick(void)
{
    md_adc_done_mask = 0U;
    ADC1->CR |= ADC_CR_JADSTART;
    ADC2->CR |= ADC_CR_JADSTART;
    ADC3->CR |= ADC_CR_JADSTART;
    ADC4->CR |= ADC_CR_JADSTART;
}

/* ---------------------------------------------------------------------------
 * System status (1 Hz CSV append): PA8 rail monitor + die temperature on
 * ADC5 — intentionally an ADC the detector circuit doesn't use. Blocking
 * injected read of 3 channels (~18 us at 247.5-cycle sampling, task
 * context only). PA8 sees its rail through a 10k series / 1k-to-ground
 * divider (x11). VREFINT is read alongside so VDDA is computed from the
 * factory-calibrated bandgap each time; temp uses TS_CAL1/TS_CAL2 (30 C /
 * 130 C points, both calibrated at VREF+ = 3.0 V).
 * ------------------------------------------------------------------------- */
#define MD_STATUS_DIVIDER    11.0f    /* (10k + 1k) / 1k                    */
#define MD_ADC5_CH_VIN       1U       /* PA8 = ADC5_IN1                     */
#define MD_ADC5_CH_TEMP      4U       /* temp sensor = ADC5_IN4             */
#define MD_ADC5_CH_VREFINT   18U      /* VREFINT = ADC5_IN18                */
#define MD_ADC_SMP_247CYC5   6U       /* temp sensor needs >= 5 us sampling */

static void md_status_init(void)
{
    HAL_ADCEx_Calibration_Start(&hadc5, ADC_SINGLE_ENDED);

    /* Route VREFINT to IN18 (VSENSESEL for the temp sensor was already set
     * by the CubeMX channel config). */
    ADC345_COMMON->CCR |= ADC_CCR_VREFEN;

    ADC5->SMPR1 = (ADC5->SMPR1
                   & ~((7U << (3U * MD_ADC5_CH_VIN))
                     | (7U << (3U * MD_ADC5_CH_TEMP))))
                  | (MD_ADC_SMP_247CYC5 << (3U * MD_ADC5_CH_VIN))
                  | (MD_ADC_SMP_247CYC5 << (3U * MD_ADC5_CH_TEMP));
    ADC5->SMPR2 = (ADC5->SMPR2
                   & ~(7U << (3U * (MD_ADC5_CH_VREFINT - 10U))))
                  | (MD_ADC_SMP_247CYC5 << (3U * (MD_ADC5_CH_VREFINT - 10U)));

    /* Injected sequence: VIN, TEMP, VREFINT; software-triggered (JEXTEN=0) */
    ADC5->JSQR = ADC_JSQR_JL_1                          /* JL=2 -> 3 convs  */
               | (MD_ADC5_CH_VIN     << ADC_JSQR_JSQ1_Pos)
               | (MD_ADC5_CH_TEMP    << ADC_JSQR_JSQ2_Pos)
               | (MD_ADC5_CH_VREFINT << ADC_JSQR_JSQ3_Pos);

    ADC5->ISR = ADC_ISR_ADRDY;
    ADC5->CR |= ADC_CR_ADEN;
    while (!(ADC5->ISR & ADC_ISR_ADRDY)) {}
}

void md_status_read(float *vin_volts, float *temp_c)
{
    ADC5->ISR = ADC_ISR_JEOS | ADC_ISR_JEOC;
    ADC5->CR |= ADC_CR_JADSTART;
    while (!(ADC5->ISR & ADC_ISR_JEOS)) {}              /* ~18 us           */
    uint32_t raw_vin  = ADC5->JDR1;
    uint32_t raw_temp = ADC5->JDR2;
    uint32_t raw_vref = ADC5->JDR3;
    ADC5->ISR = ADC_ISR_JEOS | ADC_ISR_JEOC;

    if (raw_vref == 0U)                                 /* broken bandgap   */
        raw_vref = 1U;

    /* Actual VDDA from the bandgap: cal value was taken at 3.0 V */
    float vdda = 3.0f * (float)(*VREFINT_CAL_ADDR) / (float)raw_vref;

    /* Scale the temp reading into the 3.0 V calibration domain, then
     * interpolate between the two factory points. */
    float ts = (float)raw_temp * vdda / 3.0f;
    *temp_c = 30.0f + (130.0f - 30.0f)
              * (ts - (float)(*TEMPSENSOR_CAL1_ADDR))
              / ((float)(*TEMPSENSOR_CAL2_ADDR) - (float)(*TEMPSENSOR_CAL1_ADDR));

    *vin_volts = (float)raw_vin / 4095.0f * vdda * MD_STATUS_DIVIDER;
}

/* ---------------------------------------------------------------------------
 * Flash settings storage — append-log in the last 4 KB page (page 31 at
 * 0x0801F000; the linker FLASH region is shrunk to 124K so the app image
 * can never grow into it). Each save appends one 32-byte record; the page
 * is erased only when all 128 slots are used, so the ~22 ms single-bank
 * erase stall (CPU can't fetch from flash during erase) almost never
 * happens. Loading takes the last valid record; a blank page = defaults.
 * ------------------------------------------------------------------------- */
#define MD_SETTINGS_PAGE_ADDR  0x0801F000UL
#define MD_SETTINGS_PAGE       31U            /* 4 KB pages, DBANK=0        */
#define MD_SETTINGS_MAGIC      0x3354444DUL   /* 'MDT3'                     */

typedef struct __attribute__((aligned(8))) {
    uint32_t magic;
    uint32_t blanking_us;          /* bits 23:0 blanking; bits 31:24 fire
                                      mode (0 = pre-fire-mode record ->
                                      MD_FIRE_BOTH applies)               */
    uint32_t rx_window_us;
    uint32_t coil_spacing_mm;      /* 0xFFFFFFFF = pre-geometry record     */
    int32_t  coil_offset_fore_mm;  /* array center vs antenna, + forward   */
    int32_t  coil_offset_right_mm; /* + starboard                          */
    uint32_t tx_pulse_us;          /* was the spare word: 0xFFFFFFFF in
                                      older records -> default applies     */
    uint32_t check;                /* ~(XOR of the 7 words above)          */
} md_settings_rec_t;               /* 32 bytes = 4 flash doublewords       */

#define MD_SETTINGS_SLOTS  (4096U / sizeof(md_settings_rec_t))

static uint32_t md_settings_check(const md_settings_rec_t *r)
{
    const uint32_t *w = (const uint32_t *)r;
    uint32_t x = 0U;
    for (uint32_t i = 0U; i < 7U; i++)
        x ^= w[i];
    return ~x;
}

static const md_settings_rec_t *md_settings_slot(uint32_t i)
{
    return (const md_settings_rec_t *)(MD_SETTINGS_PAGE_ADDR
                                       + i * sizeof(md_settings_rec_t));
}

/* A save cut by power loss can leave a doubleword with invalid ECC; any
 * read of it (e.g. the boot-time slot scan) raises an ECC double-error
 * NMI. Without this hook the stock NMI handler hangs forever — a bricked
 * unit. Called from NMI_Handler: if the failing address is inside the
 * settings page, clear the flags, note the fault, and resume (the read
 * returned garbage, which magic/checksum reject); MD_Load_Settings then
 * purges the page. Any other NMI cause returns 0 → original hang. */
static volatile uint32_t md_settings_ecc_fault = 0U;

uint32_t MD_Settings_ECC_NMI(void)
{
    uint32_t eccr = FLASH->ECCR;
    if (!(eccr & (FLASH_ECCR_ECCD | FLASH_ECCR_ECCD2)))
        return 0U;

    /* DBANK=0: ADDR_ECC = byte offset (from flash base) of the failing
     * 128-bit quad word, low 4 bits cleared (RM0440 3.3.2). */
    uint32_t off = eccr & FLASH_ECCR_ADDR_ECC;
    if (off <  (MD_SETTINGS_PAGE_ADDR - FLASH_BASE) ||
        off >= (MD_SETTINGS_PAGE_ADDR - FLASH_BASE) + 4096U)
        return 0U;                     /* ECC fault outside our page       */

    FLASH->ECCR = eccr | FLASH_ECCR_ECCD | FLASH_ECCR_ECCD2;   /* w1c     */
    md_settings_ecc_fault = 1U;
    return 1U;
}

/* Erase the settings page (also the recovery path for ECC faults). */
static void md_settings_erase_page(void)
{
    FLASH_EraseInitTypeDef erase = {
        .TypeErase = FLASH_TYPEERASE_PAGES,
        .Banks     = FLASH_BANK_1,
        .Page      = MD_SETTINGS_PAGE,
        .NbPages   = 1U,
    };
    uint32_t page_err = 0U;
    HAL_FLASH_Unlock();
    __HAL_FLASH_CLEAR_FLAG(FLASH_FLAG_SR_ERRORS);
    (void)HAL_FLASHEx_Erase(&erase, &page_err);
    HAL_FLASH_Lock();
}

void MD_Load_Settings(void)
{
    const md_settings_rec_t *last = NULL;

    for (uint32_t i = 0U; i < MD_SETTINGS_SLOTS; i++) {
        const md_settings_rec_t *r = md_settings_slot(i);
        if (r->magic == MD_SETTINGS_MAGIC && r->check == md_settings_check(r))
            last = r;                        /* newest valid record wins     */
    }

    if (md_settings_ecc_fault) {
        /* An interrupted save left invalid ECC somewhere in the page (the
         * scan's NMIs were absorbed above). Purge it and run defaults. */
        md_settings_ecc_fault = 0U;
        md_settings_erase_page();
        last = NULL;
        printf("# settings page had ECC fault -- erased, using defaults\r\n");
    }

    if (last) {
        /* Clamp to the same limits the console enforces (16-bit ARR at
         * 170 MHz ticks) in case the record came from other firmware. */
        uint32_t bl = last->blanking_us & 0x00FFFFFFU;
        uint32_t fm = last->blanking_us >> 24;
        md_blanking_us  = (bl <= MD_BLANKING_MAX_US)
                          ? bl : MD_BLANKING_MAX_US;
        /* 0 = record predates fire mode; anything else out of range means
         * foreign firmware — the default (both) applies either way. */
        md_fire_mode    = (fm >= MD_FIRE_A && fm <= MD_FIRE_BOTH)
                          ? (uint8_t)fm : (uint8_t)MD_FIRE_BOTH;
        md_rx_window_us = (last->rx_window_us >= 1U &&
                           last->rx_window_us <= MD_RX_WINDOW_MAX_US)
                          ? last->rx_window_us : MD_RX_WINDOW_US;
        /* Older records carry erased 0xFFFFFFFF in this (ex-spare) word —
         * out of range, so the compile-time default applies. */
        md_tx_pulse_us  = (last->tx_pulse_us >= MD_TX_PULSE_MIN_US &&
                           last->tx_pulse_us <= MD_TX_PULSE_MAX_US)
                          ? last->tx_pulse_us : MD_TX_PULSE_US;
        /* Records saved before the geometry fields existed have erased
         * 0xFFFFFFFF in coil_spacing_mm — keep all-default geometry then
         * (the offsets would otherwise read as -1 mm, not 0). */
        if (last->coil_spacing_mm != 0xFFFFFFFFU) {
            md_coil_spacing_mm =
                (last->coil_spacing_mm >= MD_COIL_SPACING_MM_MIN &&
                 last->coil_spacing_mm <= MD_COIL_SPACING_MM_MAX)
                ? last->coil_spacing_mm : MD_COIL_SPACING_MM_DEFAULT;
            md_coil_offset_fore_mm =
                (last->coil_offset_fore_mm  >= -MD_COIL_OFFSET_MM_LIMIT &&
                 last->coil_offset_fore_mm  <=  MD_COIL_OFFSET_MM_LIMIT)
                ? last->coil_offset_fore_mm : 0;
            md_coil_offset_right_mm =
                (last->coil_offset_right_mm >= -MD_COIL_OFFSET_MM_LIMIT &&
                 last->coil_offset_right_mm <=  MD_COIL_OFFSET_MM_LIMIT)
                ? last->coil_offset_right_mm : 0;
        }
        printf("# settings loaded: blanking=%luus  rx_window=%luus  tx_pulse=%luus  coil_spacing=%lumm  fire_mode=%s\r\n",
               md_blanking_us, md_rx_window_us, md_tx_pulse_us, md_coil_spacing_mm,
               md_fire_name(md_fire_mode));
    } else {
        /* Nothing valid in flash (new board, or the page was just purged
         * after an ECC fault): persist the compile-time defaults so the
         * unit always carries a valid record. 'D' re-writes them on demand. */
        printf("# no saved settings -- writing defaults: blanking=%luus  rx_window=%luus  tx_pulse=%luus  coil_spacing=%lumm  fire_mode=%s\r\n",
               md_blanking_us, md_rx_window_us, md_tx_pulse_us, md_coil_spacing_mm,
               md_fire_name(md_fire_mode));
        MD_Save_Settings();
    }
}

void MD_Save_Settings(void)
{
    /* Hold the pacer off so no cycle STARTS mid-save (flash ops stall the
     * bus and would defer the timeline's ADC kick). A fire that lands
     * during the save pends and runs right after re-enable. Harmless
     * before md_pace_init (first-boot default write): nothing pends. */
    HAL_NVIC_DisableIRQ(TIM7_DAC_IRQn);

    /* A cycle started just before the disable may still be in flight; the
     * flash stall would defer its ADC kick too, sampling integrators that
     * drooped for the whole operation (~22 ms on a page erase). Wait it
     * out: a full cycle is ~150 us, the tick bound is a safety valve. The
     * TIM1 UIF term covers a kick that is pended but not yet taken. */
    uint32_t t0 = HAL_GetTick();
    while ((((TIM2->CR1 | TIM3->CR1 | TIM1->CR1 | TIM8->CR1) & TIM_CR1_CEN)
            || (TIM1->SR & TIM_SR_UIF)
            || md_adc_done_mask != 0x0FU)
           && (HAL_GetTick() - t0) < 2U) {}

    /* First fully-erased slot; page full -> erase and restart at slot 0. */
    uint32_t slot = MD_SETTINGS_SLOTS;
    for (uint32_t i = 0U; i < MD_SETTINGS_SLOTS && slot == MD_SETTINGS_SLOTS; i++) {
        const uint32_t *w = (const uint32_t *)md_settings_slot(i);
        uint32_t j;
        for (j = 0U; j < 8U; j++)
            if (w[j] != 0xFFFFFFFFU)
                break;
        if (j == 8U)
            slot = i;
    }

    md_settings_rec_t rec;
    memset(&rec, 0xFF, sizeof(rec));
    rec.magic                = MD_SETTINGS_MAGIC;
    rec.blanking_us          = md_blanking_us
                             | ((uint32_t)md_fire_mode << 24);
    rec.rx_window_us         = md_rx_window_us;
    rec.tx_pulse_us          = md_tx_pulse_us;
    rec.coil_spacing_mm      = md_coil_spacing_mm;
    rec.coil_offset_fore_mm  = md_coil_offset_fore_mm;
    rec.coil_offset_right_mm = md_coil_offset_right_mm;
    rec.check                = md_settings_check(&rec);

    HAL_FLASH_Unlock();

    /* Clear stale SR error flags — notably OPTVERR, which the option-byte
     * loader can leave set at reset; the HAL's entry check would otherwise
     * fail the first program/erase after boot. */
    __HAL_FLASH_CLEAR_FLAG(FLASH_FLAG_SR_ERRORS);

    if (slot == MD_SETTINGS_SLOTS) {
        FLASH_EraseInitTypeDef erase = {
            .TypeErase = FLASH_TYPEERASE_PAGES,
            .Banks     = FLASH_BANK_1,
            .Page      = MD_SETTINGS_PAGE,
            .NbPages   = 1U,
        };
        uint32_t page_err = 0U;
        if (HAL_FLASHEx_Erase(&erase, &page_err) != HAL_OK) {
            HAL_FLASH_Lock();
            HAL_NVIC_EnableIRQ(TIM7_DAC_IRQn);
            printf("# save FAILED: page erase error 0x%08lx\r\n", page_err);
            return;
        }
        slot = 0U;
    }

    HAL_StatusTypeDef st = HAL_OK;
    const uint64_t *src = (const uint64_t *)&rec;
    uint32_t dst = MD_SETTINGS_PAGE_ADDR + slot * sizeof(rec);
    for (uint32_t i = 0U; i < 4U && st == HAL_OK; i++)
        st = HAL_FLASH_Program(FLASH_TYPEPROGRAM_DOUBLEWORD,
                               dst + 8U * i, src[i]);

    /* HAL_FLASHEx_Erase flushes the ART caches but HAL_FLASH_Program does
     * not: without this, the readback below (and the next save's free-slot
     * scan) can see stale erased 0xFFs from the data cache — the scan would
     * then re-program a written doubleword, which G4 ECC forbids. */
    __HAL_FLASH_DATA_CACHE_DISABLE();
    __HAL_FLASH_DATA_CACHE_RESET();
    __HAL_FLASH_DATA_CACHE_ENABLE();

    HAL_FLASH_Lock();
    HAL_NVIC_EnableIRQ(TIM7_DAC_IRQn);

    const md_settings_rec_t *r = md_settings_slot(slot);
    if (st == HAL_OK && r->magic == MD_SETTINGS_MAGIC
        && r->check == md_settings_check(r))
        printf("# saved (slot %lu/%u): blanking=%luus  rx_window=%luus  tx_pulse=%luus  coil_spacing=%lumm  fire_mode=%s\r\n",
               slot, (unsigned)MD_SETTINGS_SLOTS,
               md_blanking_us, md_rx_window_us, md_tx_pulse_us, md_coil_spacing_mm,
               md_fire_name(md_fire_mode));
    else
        printf("# save FAILED: program/verify at slot %lu\r\n", slot);
}

/* ---------------------------------------------------------------------------
 * 'I' info line: everything the daemon stamps into a study header. One
 * space-separated key=value line, parse-friendly; "?" marks a value the
 * GPS module never reported. Task context only (printf).
 * ------------------------------------------------------------------------- */
void md_print_info(void)
{
    printf("# info fw=%s gps_ver=%s gps_id=%s"
           " blanking_us=%lu rx_window_us=%lu tx_pulse_us=%lu"
           " coil_spacing_mm=%lu coil_offset_fore_mm=%ld coil_offset_right_mm=%ld"
           " fire_mode=%s adc_oversample=16 adc=PA0,PA1,PA6,PA7,PB1,PB13,PB12,PB14\r\n",
           FW_GIT_HASH,
           gps_version_str[0] ? gps_version_str : "?",
           gps_uniqid_str[0]  ? gps_uniqid_str  : "?",
           md_blanking_us, md_rx_window_us, md_tx_pulse_us,
           md_coil_spacing_mm,
           (long)md_coil_offset_fore_mm, (long)md_coil_offset_right_mm,
           md_fire_name(md_fire_mode));
}

/* Console key map — printed at boot so the bindings are on screen for
 * anyone at the console. Deliberately no 'key=value' tokens, so the
 * daemon's info/echo parsers can never match these lines. */
void md_print_keys(void)
{
    printf("# keys: a/z blanking +-2us (0..200)    s/x rx window +-1us (1..50)\r\n"
           "# keys: f/v tx pulse +-1us (10..120)   d/c coil spacing +-10mm (50..5000)\r\n"
           "# keys: 1/2/3 fire coils: odd only (PA5) / even only (PB4) / both\r\n"
           "# keys: S save settings   D restore defaults+save   I info   G gps passthrough\r\n");
}

/* ---------------------------------------------------------------------------
 * Console: poll USART1 RX from the task loop (detector2 pattern — direct
 * register access, no HAL receive state machine to wedge, no ISR). Drain
 * everything each poll so held keys adjust smoothly; print once.
 *
 * Upper clamps (MD_*_MAX_US) are new on this board — see their definition.
 * ------------------------------------------------------------------------- */
void md_console_poll(void)
{
    USART1->ICR = USART_ICR_ORECF | USART_ICR_FECF
                | USART_ICR_NECF | USART_ICR_PECF;

    int changed = 0;
    int geom_changed = 0;
    int tx_changed = 0;
    int fire_changed = 0;
    while (USART1->ISR & USART_ISR_RXNE) {
        uint8_t ch = (uint8_t)(USART1->RDR & 0xFFU);
        if      (ch == 'a') { if (md_blanking_us < MD_BLANKING_MAX_US) md_blanking_us += 2U;            changed = 1; }
        else if (ch == 'z') { md_blanking_us  = (md_blanking_us  > 2U) ? md_blanking_us - 2U : 0U;      changed = 1; }
        else if (ch == 's') { if (md_rx_window_us < MD_RX_WINDOW_MAX_US) md_rx_window_us += 1U;         changed = 1; }
        else if (ch == 'x') { md_rx_window_us = (md_rx_window_us > 1U) ? md_rx_window_us - 1U : 1U;     changed = 1; }
        else if (ch == 'd') { if (md_coil_spacing_mm < MD_COIL_SPACING_MM_MAX) md_coil_spacing_mm += 10U; geom_changed = 1; }
        else if (ch == 'c') { if (md_coil_spacing_mm > MD_COIL_SPACING_MM_MIN) md_coil_spacing_mm -= 10U; geom_changed = 1; }
        else if (ch == 'f') { if (md_tx_pulse_us < MD_TX_PULSE_MAX_US) md_tx_pulse_us += 1U;            tx_changed = 1; }
        else if (ch == 'v') { if (md_tx_pulse_us > MD_TX_PULSE_MIN_US) md_tx_pulse_us -= 1U;            tx_changed = 1; }
        else if (ch == '1') { md_fire_mode = MD_FIRE_A;    fire_changed = 1; }
        else if (ch == '2') { md_fire_mode = MD_FIRE_B;    fire_changed = 1; }
        else if (ch == '3') { md_fire_mode = MD_FIRE_BOTH; fire_changed = 1; }
        else if (ch == 'S') { MD_Save_Settings(); }
        else if (ch == 'D') {
            /* Force-restore compile-time defaults and persist them. */
            md_blanking_us          = MD_BLANKING_US;
            md_rx_window_us         = MD_RX_WINDOW_US;
            md_tx_pulse_us          = MD_TX_PULSE_US;
            md_coil_spacing_mm      = MD_COIL_SPACING_MM_DEFAULT;
            md_coil_offset_fore_mm  = 0;
            md_coil_offset_right_mm = MD_COIL_OFFSET_RIGHT_MM_DEFAULT;
            md_fire_mode            = MD_FIRE_BOTH;
            printf("# defaults restored\r\n");
            MD_Save_Settings();
        }
        else if (ch == 'I') { md_print_info(); }
        else if (ch == 'G') {
            gps_passthrough_enabled = !gps_passthrough_enabled;
            printf("# gps passthrough %s\r\n",
                   gps_passthrough_enabled ? "on" : "off");
        }
    }
    if (changed)
        printf("# blanking=%luus  rx_window=%luus\r\n",
               md_blanking_us, md_rx_window_us);
    if (tx_changed)
        printf("# tx_pulse=%luus\r\n", md_tx_pulse_us);
    if (geom_changed)
        printf("# coil_spacing=%lumm\r\n", md_coil_spacing_mm);
    if (fire_changed)
        printf("# fire_mode=%s\r\n", md_fire_name(md_fire_mode));
}

/* Common one-pulse timebase setup: 170 MHz ticks, given end-of-timeline. */
static void md_opm_timebase(TIM_TypeDef *tim, uint32_t arr)
{
    tim->CR1 &= ~TIM_CR1_CEN;
    tim->CR1 |= TIM_CR1_OPM;
    tim->PSC  = 0U;
    tim->ARR  = arr;
    tim->CNT  = 0U;
    tim->EGR  = TIM_EGR_UG;    /* latch PSC now                             */
    tim->SR   = 0U;            /* clear UG-induced UIF and stale flags      */
}

static void md_pace_init(void);   /* TIM7 cycle pacer — defined below */

/* ============================================================================
 * MD_Hardware_Init
 * Called once from the app task after all MX_ inits. Overrides the CubeMX
 * baseline with the hardware-timeline configuration; all pins idle.
 * ========================================================================== */
void MD_Hardware_Init(void)
{
    MD_Load_Settings();   /* apply saved timing before first cycle */

    const uint32_t tx_arr  = md_tx_pulse_us * MD_TICKS_PER_US;
    const uint32_t aux_arr = (md_tx_pulse_us + md_blanking_us + md_rx_window_us)
                             * MD_TICKS_PER_US;

    /* ---------------- TIM2: master + Set A TX (PA5) ------------------- */
    md_opm_timebase(TIM2, tx_arr);
    TIM2->CR2 = (TIM2->CR2 & ~TIM_CR2_MMS) | TIM_CR2_MMS_0;  /* TRGO = CEN  */
    TIM2->CCR1 = 1U;                       /* TX rise one tick after start  */
    md_oc_mode(TIM2, 1, MD_OCM_FORCE_INACT);
    TIM2->CCER |= TIM_CCER_CC1E;
    TIM2->DIER  = 0U;                      /* no interrupts on TX timers    */

    /* ---------------- TIM3: slave + Set B TX (PB4) -------------------- */
    md_opm_timebase(TIM3, tx_arr);
    md_slave_to_tim2(TIM3);
    TIM3->CCR1 = 1U;
    md_oc_mode(TIM3, 1, MD_OCM_FORCE_INACT);
    TIM3->CCER |= TIM_CCER_CC1E;
    TIM3->DIER  = 0U;

    /* ---------------- TIM1: slave + Set A aux (PA9/PA10/PA11) --------- */
    md_opm_timebase(TIM1, aux_arr);
    md_slave_to_tim2(TIM1);
    md_oc_mode(TIM1, 2, MD_OCM_FORCE_INACT);   /* PA9  LOW  (gain-protect) */
    md_oc_mode(TIM1, 3, MD_OCM_FORCE_INACT);   /* PA10 LOW  (integ reset)  */
    md_oc_mode(TIM1, 4, MD_OCM_FORCE_INACT);   /* PA11 HIGH (RX off, CC4P) */
    TIM1->CCER |= TIM_CCER_CC2E | TIM_CCER_CC3E | TIM_CCER_CC4E | TIM_CCER_CC4P;
    TIM1->CR2  &= ~(TIM_CR2_OIS2 | TIM_CR2_OIS3 | TIM_CR2_OIS4);
    TIM1->BDTR |= TIM_BDTR_MOE | TIM_BDTR_OSSR | TIM_BDTR_OSSI;
    TIM1->DIER  = TIM_DIER_UIE;
    HAL_NVIC_SetPriority(TIM1_UP_TIM16_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM1_UP_TIM16_IRQn);

    /* ---------------- TIM8: slave + Set B aux (PA15/PB9/PC13) --------- */
    md_opm_timebase(TIM8, aux_arr);
    md_slave_to_tim2(TIM8);
    md_oc_mode(TIM8, 1, MD_OCM_FORCE_INACT);   /* PA15 LOW  (gain-protect) */
    md_oc_mode(TIM8, 3, MD_OCM_FORCE_INACT);   /* PB9  LOW  (integ reset)  */
    md_oc_mode(TIM8, 4, MD_OCM_FORCE_INACT);   /* PC13 HIGH (RX off, CC4NP)*/
    TIM8->CCER |= TIM_CCER_CC1E | TIM_CCER_CC3E | TIM_CCER_CC4NE | TIM_CCER_CC4NP;
    TIM8->CR2  &= ~(TIM_CR2_OIS1 | TIM_CR2_OIS3 | TIM_CR2_OIS4N);
    TIM8->BDTR |= TIM_BDTR_MOE | TIM_BDTR_OSSR | TIM_BDTR_OSSI;
    TIM8->DIER  = TIM_DIER_UIE;
    HAL_NVIC_SetPriority(TIM8_UP_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM8_UP_IRQn);

    /* ---------------- ADC1..4: injected pairs, all 8 inputs ----------- */
    md_adc_init();

    /* ---------------- ADC5: 1 Hz status (PA8 / temp / VREFINT) -------- */
    md_status_init();

    /* ---------------- TIM7: GPS-synchronised cycle pacing ------------- */
    md_pace_init();
}

/* Arm one set for the coming cycle (timers are stopped here, so mode and
 * compare writes are glitch-free). The aux channels are armed identically
 * every cycle in every mode; fire_tx gates only the coil trigger. */
static void md_arm_set(md_set_t *s, uint8_t fire_tx,
                       uint32_t tx_arr, uint32_t aux_ccr, uint32_t aux_arr)
{
    s->tx->ARR  = tx_arr;
    s->opm->ARR = aux_arr;
    md_set_ccr(s->opm, s->gain_ch,  aux_ccr);
    md_set_ccr(s->opm, s->integ_ch, aux_ccr);
    md_set_ccr(s->opm, s->rx_ch,    aux_ccr);

    /* Reset refs LOW first so re-arming can't glitch, then arm. */
    md_oc_mode(s->opm, s->gain_ch,  MD_OCM_FORCE_INACT);
    md_oc_mode(s->opm, s->integ_ch, MD_OCM_FORCE_INACT);
    md_oc_mode(s->opm, s->gain_ch,  MD_OCM_ACT_ON_CMP);  /* latches HIGH      */
    md_oc_mode(s->opm, s->integ_ch, MD_OCM_ACT_ON_CMP);  /* latches HIGH      */
    md_oc_mode(s->opm, s->rx_ch,    MD_OCM_PWM2);        /* hardware window   */

    /* The only per-mode difference: does this coil fire? */
    md_oc_mode(s->tx, 1, fire_tx ? MD_OCM_PWM2           /* rise @1 tick,
                                                            fall @update      */
                                 : MD_OCM_FORCE_INACT);  /* coil quiet        */
}

/* ============================================================================
 * md_start_cycle  (called from the TIM7 pacer IRQ — see md_pace_fired)
 * Arms the selected set(s), then starts the master. Every armed timer
 * starts on the same hardware trigger — the only software-timed event is
 * this single CEN write, and nothing downstream depends on when it lands.
 * ========================================================================== */
uint8_t md_start_cycle(md_fire_t which)
{
    if (((TIM2->CR1 | TIM3->CR1 | TIM1->CR1 | TIM8->CR1) & TIM_CR1_CEN)
        || md_adc_done_mask != 0x0FU)
        return 0U;            /* previous cycle (timers or ADC) still running */

    uint32_t tx = md_tx_pulse_us;
    uint32_t bl = md_blanking_us;
    uint32_t rx = md_rx_window_us;
    uint32_t tx_arr  = tx * MD_TICKS_PER_US;
    uint32_t aux_ccr = (tx + bl) * MD_TICKS_PER_US + 1U;
    uint32_t aux_arr = (tx + bl + rx) * MD_TICKS_PER_US;

    md_arm_set(&md_set_a, (which & MD_FIRE_A) != 0U, tx_arr, aux_ccr, aux_arr);
    md_arm_set(&md_set_b, (which & MD_FIRE_B) != 0U, tx_arr, aux_ccr, aux_arr);

    md_ts_cen = dwt_cyccnt();
    TIM2->CR1 |= TIM_CR1_CEN;      /* master + all armed slaves start here   */
    return 1U;
}

/* ============================================================================
 * OPM expiry (UIE at end of RX window). Every critical edge this cycle
 * already happened in hardware — the RX disconnect was the PWM2 self-clear
 * at this same update event. TIM1 runs the timeline in every fire mode, so
 * its UIE does the cycle-wide work: start all four ADC injected sequences.
 * ========================================================================== */
void md_tim1_uie_fired(void)
{
    md_ts_opm = dwt_cyccnt();
    md_adc_kick();
}

void md_tim8_uie_fired(void)
{
    /* nothing — TIM1's UIE covers the cycle; kept for future per-set work */
}

/* ============================================================================
 * Cycle pacing (TIM7, basic timer, one-pulse @ 10 kHz timebase).
 * See metal_detector.h for the cadence contract. Both arm sites — the GPS
 * fix path (USART2 IRQ) and TIM7's own expiry — run at NVIC priority 6, so
 * they serialize and the state below needs no further locking. (The one
 * exception is md_pace_init's boot-time arm, task context: an early fix
 * can interleave, but every interleaving still leaves the timer armed —
 * worst case is one odd first interval, re-synced by the next fix.)
 * ========================================================================== */
#define MD_PACE_TICKS_PER_MS 10U

volatile uint8_t md_idle_line_due = 0U;

static volatile uint8_t md_pace_remaining = 0U; /* extra fires this interval */
static volatile uint8_t md_pace_idle = 1U;      /* current arm is idle-rate  */

/* An expiry that lands while the other arm site runs (equal priority, so
 * it can only pend, never preempt) is superseded by this re-arm: clearing
 * SR alone is not enough — the NVIC latches pending on the UIF edge and
 * only exception entry or an ICPR write releases it. The SR readback
 * orders the flag clear ahead of the pend clear so the still-asserted
 * line can't re-latch. */
static void md_pace_arm(uint32_t ms)
{
    TIM7->CR1 &= ~TIM_CR1_CEN;
    TIM7->ARR  = ms * MD_PACE_TICKS_PER_MS - 1U;
    TIM7->EGR  = TIM_EGR_UG;   /* latch ARR, reset CNT (URS: no UIF)   */
    TIM7->SR   = 0U;           /* drop a stale expiry UIF              */
    (void)TIM7->SR;            /* drain the posted SR write            */
    HAL_NVIC_ClearPendingIRQ(TIM7_DAC_IRQn);
    TIM7->CR1 |= TIM_CR1_CEN;
}

static void md_pace_init(void)
{
    __HAL_RCC_TIM7_CLK_ENABLE();
    TIM7->PSC  = (170000U / MD_PACE_TICKS_PER_MS) - 1U;  /* 170 MHz -> 10 kHz */
    /* URS: md_pace_arm's UG reloads PSC/CNT without raising UIF — with
     * UIE live, a UG-induced UIF would pend the IRQ in the NVIC faster
     * than the SR clear can catch it. Only a real expiry interrupts. */
    TIM7->CR1  = TIM_CR1_OPM | TIM_CR1_URS;
    TIM7->DIER = TIM_DIER_UIE;
    HAL_NVIC_SetPriority(TIM7_DAC_IRQn, 6, 0);   /* == USART2 (GPS) priority */
    HAL_NVIC_EnableIRQ(TIM7_DAC_IRQn);
    md_pace_arm(1U);   /* first frame right away; idle cadence follows */
}

void md_pace_on_fix(void)
{
    md_pace_idle = 0U;
    md_idle_line_due = 0U;   /* stale idle flag: this frame reports via GGA */
    md_pace_remaining = MD_SAMPLES_PER_GPS_PERIOD - 1U;
    md_pace_arm(MD_GPS_PERIOD_MS / MD_SAMPLES_PER_GPS_PERIOD
                - MD_SAMPLE_LEAD_MS);
}

void md_pace_fired(void)
{
    if ((TIM7->SR & TIM_SR_UIF) == 0U)
        return;                             /* superseded expiry (see arm) */
    TIM7->SR = 0U;                          /* clear UIF */
    md_adc_frame_ready = 0U;                /* frame in flight */
    md_start_cycle((md_fire_t)md_fire_mode);
    if (md_pace_idle)
        md_idle_line_due = 1U;              /* no fix armed this one */
    if (md_pace_remaining != 0U) {
        md_pace_remaining--;
        md_pace_arm(MD_GPS_PERIOD_MS / MD_SAMPLES_PER_GPS_PERIOD);
    } else {
        /* Fallback arm: a valid fix normally re-arms before this fires;
         * without one it keeps frames (and idle lines) coming at the
         * idle rate with the coils resting in between. */
        md_pace_idle = 1U;
        md_pace_arm(MD_IDLE_PERIOD_MS);
    }
}

/* ============================================================================
 * Injected-sequence completion (JEOS), one per ADC. The last one to land
 * releases gain + integ on both sets: every integrator has been sampled by
 * then. For a disabled set the releases are no-ops (refs already inactive).
 * ========================================================================== */
static void md_adc_collect(uint32_t i)
{
    const md_adc_pair_t *p = &md_adc_pairs[i];

    p->adc->ISR = ADC_ISR_JEOS | ADC_ISR_JEOC;          /* clear flags       */
    md_adc[p->idx]      = (uint16_t)p->adc->JDR1;
    md_adc[p->idx + 1U] = (uint16_t)p->adc->JDR2;

    uint8_t done = md_adc_done_mask | (uint8_t)(1U << i);
    md_adc_done_mask = done;
    if (done == 0x0FU) {
        md_oc_mode(md_set_a.opm, md_set_a.gain_ch,  MD_OCM_FORCE_INACT);
        md_oc_mode(md_set_a.opm, md_set_a.integ_ch, MD_OCM_FORCE_INACT);
        md_oc_mode(md_set_b.opm, md_set_b.gain_ch,  MD_OCM_FORCE_INACT);
        md_oc_mode(md_set_b.opm, md_set_b.integ_ch, MD_OCM_FORCE_INACT);
        md_cycle_count++;
        md_adc_frame_ready = 1U;
    }
}

/* Raw IRQ hooks — called from the handlers in stm32g4xx_it.c USER CODE 1 */
void md_adc12_irq(void)
{
    if (ADC1->ISR & ADC_ISR_JEOS) md_adc_collect(0U);
    if (ADC2->ISR & ADC_ISR_JEOS) md_adc_collect(1U);
}

void md_adc3_irq(void)
{
    if (ADC3->ISR & ADC_ISR_JEOS) md_adc_collect(2U);
}

void md_adc4_irq(void)
{
    if (ADC4->ISR & ADC_ISR_JEOS) md_adc_collect(3U);
}
