#!/bin/sh
# Regenerate Core/Inc/fw_version.h from git (short hash, "-dirty" suffix
# when the working tree has uncommitted changes). Wired in as the
# pre-build step of both build configurations (.cproject prebuildStep
# for the IDE, the pre-build target in Debug/Release makefiles for
# command-line `make all`), so every build refreshes the hash.
#
# The header is gitignored; code falls back to "unknown" via
# __has_include when it is absent, so builds never break without it.
cd "$(dirname "$0")" || exit 1

# Short HEAD hash; "-dirty" only if THIS subtree has uncommitted changes
# (unrelated edits elsewhere in the repo shouldn't taint the fw version).
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
if [ "$HASH" != "unknown" ] && ! git diff --quiet HEAD -- . 2>/dev/null; then
  HASH="$HASH-dirty"
fi
OUT=Core/Inc/fw_version.h

NEW="/* Auto-generated by gen_version.sh -- do not edit, not committed. */
#ifndef FW_VERSION_H
#define FW_VERSION_H
#define FW_GIT_HASH \"$HASH\"
#endif"

# Only rewrite on change so unchanged builds stay incremental.
if [ ! -f "$OUT" ] || [ "$NEW" != "$(cat "$OUT")" ]; then
  printf '%s\n' "$NEW" > "$OUT"
fi
